### ISSUE TITLE
Synctex Doesn't Work

### ISSUE THREAD

**Issue by manoyes** [overleaf/clsi#11]
On my Ubuntu 14.04 LTS Virtual Machine, when I try to find a position in the PDF from source, or find a position in the source from the PDF, by double-clicking in the PDF or clicking the arrow keys, nothing happens. I assume this has to do with Synctex not being found by the CLSI application.

I installed Sharelatex and its dependencies (including Texlive) on Ubuntu 14.04 using the [installation instructions for Ubuntu 13.03](https://github.com/sharelatex/sharelatex/wiki/Installation-instructions-for-Ubuntu-13.10).

When I try this functionality, the following logs are produced (notice the error from CLSI):

```
[2014-08-12T22:44:26.444Z]  INFO: web-sharelatex/1147 on corriv: Checking if can access
    user: {
      "id": "53def8672a2968d8209f6742",
      "email": "example@example.com"
    }
    --
    project: {
      "id": "53e534d75cfc01960965b2ec",
      "name": "Test"
    }
[2014-08-12T22:44:26.444Z]  INFO: web-sharelatex/1147 on corriv: proxying to CLSI
    url: /project/53e534d75cfc01960965b2ec/sync/code?column=240&file=main.tex&line=232
[2014-08-12T22:44:26.459Z]  INFO: web-sharelatex/1147 on corriv: http request (response-time=21, req.remote-addr=127.0.0.1)
    GET /project/53e534d75cfc01960965b2ec/sync/code?column=240&file=main.tex&line=232 HTTP/1.1
    --
    req.referrer: http://corriv.jsc.nasa.gov/project/53e534d75cfc01960965b2ec
    --
    req.user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/7.0.5 Safari/537.77.4
[2014-08-12T22:44:34.309Z]  INFO: web-sharelatex/1147 on corriv: marking user as connected (project_id=53e534d75cfc01960965b2ec, client_id=48-jsQAIE77SYg0fXM0l)
2014-08-12T22:44:41.202Z]  INFO: web-sharelatex/1147 on corriv: mongo request (query_type=query, collection=sharelatex.projects, response-time=3)
    query: {
      "_id": "53e534d75cfc01960965b2ec"
    }
[2014-08-12T22:44:41.219Z] ERROR: clsi/1163 on corriv: server error
    Error: spawn ENOENT
        at errnoException (child_process.js:1001:11)
        at Process.ChildProcess._handle.onexit (child_process.js:792:34)
[2014-08-12T22:44:41.209Z]  INFO: web-sharelatex/1147 on corriv: mongo request (query_type=query, collection=sharelatex.users, response-time=2)
    query: {
      "_id": "53def8672a2968d8209f6742"
    }
[2014-08-12T22:44:41.210Z]  INFO: web-sharelatex/1147 on corriv: Checking if can access
    user: {
      "id": "53def8672a2968d8209f6742",
      "email": "example@example.com"
    }
    --
    project: {
      "id": "53e534d75cfc01960965b2ec",
      "name": "Test"
    }
[2014-08-12T22:44:41.227Z]  INFO: clsi/1163 on corriv: http request (response-time=13, req.remote-addr=127.0.0.1)
    GET /project/53e534d75cfc01960965b2ec/sync/code?column=256&file=main.tex&line=213 HTTP/1.1
[2014-08-12T22:44:41.210Z]  INFO: web-sharelatex/1147 on corriv: proxying to CLSI
    url: /project/53e534d75cfc01960965b2ec/sync/code?column=256&file=main.tex&line=213
[2014-08-12T22:44:41.227Z]  INFO: web-sharelatex/1147 on corriv: http request (response-time=29, req.remote-addr=127.0.0.1)
    GET /project/53e534d75cfc01960965b2ec/sync/code?column=256&file=main.tex&line=213 HTTP/1.1
    --
    req.referrer: http://corriv.jsc.nasa.gov/project/53e534d75cfc01960965b2ec
    --
    req.user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/7.0.5 Safari/537.77.4
```

**Comment by Junia18** [comment]
I am facing the following error:

Running "compile:bin" task
Fatal error: spawn cc ENOENT

I am using Windows 7 OS. Please help

**Comment by manoyes** [comment]
@Junia18 If you can't install or compile zlib for Windows you could try running the ShareLaTeX server in a local virtual machine with a tool like [Vagrant](https://www.vagrantup.com/) where you can easily forward port 3000 to your host Windows OS, which lets you access the server through a browser using the localhost address. You could then use the workaround in this issue.

**Comment by Junia18** [comment]
I tried installing Vagrant but still faced the same issue. So i switched to Ubuntu 14.04 LTS. 
Since i am using a local CLSI server, Can you tell me a particular compilation request format with which we can send data to the server? 
(I am working on an android app for editing LaTeX documents)

**Comment by jpallen** [comment]
The ENOENT sounds like you might be missing the 'gcc' compiler which is used to compile the SyncTeX extension.

**Comment by pdrlps** [comment]
**Closed**, last activity on Apr 2015.
