### ISSUE TITLE
Can't compile tex files containing images

### ISSUE THREAD

**Issue by Junia18** [overleaf/clsi#19]
I am developing an android LaTeX editor. Whenever i try to compile tex file containing images, it shows "Internal Server Error"

CLSI log shows:

ERROR: clsi/4510 : server error
    SyntaxError: Unexpected string
        at Object.parse (native)
        at parse (/home/name/clsi-sharelatex/node_modules/body-parser/lib/types/json.js:84:17)
        at /home/name/clsi-sharelatex/node_modules/body-parser/lib/read.js:102:18
        at IncomingMessage.onEnd (/home/name/clsi-sharelatex/node_modules/body-parser/node_modules/raw-body/index.js:136:7)
        at IncomingMessage.g (events.js:180:16)
        at IncomingMessage.EventEmitter.emit (events.js:92:17)
        at _stream_readable.js:920:16
        at process._tickCallback (node.js:415:13)
Thu, 16 Apr 2015 14:49:08 GMT express deprecated res.send(status): Use res.sendStatus(status) instead at app.js:136:16

Can anyone help me to resolve this problem?

**Comment by pdrlps** [comment]
**Closed**, last activity on Oct 2014.
